language: php

php:
  - 5.5
  - 5.6

before_instal:
  - composer self-update

install:
  - composer install --prefer-source

before_script:
  # php linter
  - vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  # php code sniffer
  - vendor/bin/phpcs src tests --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml --ignore=bootstrap

script:
  - vendor/bin/phpunit
